# (generated with --quick)

def assert_int(var: int, name: str) -> None: ...
def decrypt_int(cyphertext: int, dkey: int, n: int) -> int: ...
def encrypt_int(message: int, ekey: int, n: int) -> int: ...
