# (generated with --quick)

from typing import List

__all__: List[str]
count: int
doctest: module
failures: int
rsa: module
tests: int

def are_relatively_prime(a: int, b: int) -> bool: ...
def gcd(p: int, q: int) -> int: ...
def get_primality_testing_rounds(number: int) -> int: ...
def getprime(nbits: int) -> int: ...
def is_prime(number: int) -> bool: ...
def miller_rabin_primality_testing(n: int, k: int) -> bool: ...
