# (generated with --quick)

common: module
os: module
struct: module
transform: module

def randint(maxvalue: int) -> int: ...
def read_random_bits(nbits: int) -> bytes: ...
def read_random_int(nbits: int) -> int: ...
def read_random_odd_int(nbits: int) -> int: ...
