# (generated with --quick)

class ExpiredSignatureError(JWTError): ...

class JOSEError(Exception): ...

class JWKError(JOSEError): ...

class JWSAlgorithmError(JWSError): ...

class JWSError(JOSEError): ...

class JWSSignatureError(JWSError): ...

class JWTClaimsError(JWTError): ...

class JWTError(JOSEError): ...
