# (generated with --quick)

from typing import Any, Type

base64: module
long: Type[int]
six: module
struct: module
sys: module

@overload
def _long_to_bytes(integer, length = ...) -> Any: ...
@overload
def _long_to_bytes(x) -> Any: ...
def base64_to_long(data) -> Any: ...
def base64url_decode(input) -> bytes: ...
def base64url_encode(input) -> bytes: ...
def calculate_at_hash(access_token, hash_alg) -> Any: ...
def int_arr_to_long(arr) -> int: ...
def long_to_base64(data, size = ...) -> bytes: ...
def long_to_bytes(n, blocksize = ...) -> Any: ...
def timedelta_total_seconds(delta) -> Any: ...
