# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "type: misc"
    commit-message:
      prefix: "ci(github)"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - "dependencies"
      - "type: misc"
    commit-message:
      prefix: "build(deps-dev)"
    schedule:
      interval: "daily"
      time: "08:00"
    allow:
      - dependency-name: "ruff"
      - dependency-name: "mypy"
      - dependency-name: "prek"
    groups:
      quality:
        patterns:
          - "ruff"
          - "ty"
          - "prek"
  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - "dependencies"
      - "type: misc"
    commit-message:
      prefix: "build(deps-test)"
    schedule:
      interval: "daily"
      time: "08:00"
    allow:
      - dependency-name: "pytest"
  - package-ecosystem: "pip"
    directory: "/"
    labels:
      - "dependencies"
      - "type: misc"
    commit-message:
      prefix: "build(deps)"
    schedule:
      interval: "daily"
      time: "08:00"
    allow:
      - dependency-name: "fastapi"
      - dependency-name: "sqlmodel"
      - dependency-name: "uvicorn"
    groups:
      quality:
        patterns:
          - "ruff"
          - "ty"
          - "prek"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    allow:
      - dependency-name: "ghcr.io/astral-sh/uv"
      - dependency-name: "localstack/localstack"
