version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "type: misc"
    commit-message:
      prefix: "ci(github)"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "uv"
    target-branch: "main"
    directory: "/"
    labels:
      - "dependencies"
      - "type: misc"
    commit-message:
      prefix: "build(deps)"
    schedule:
      interval: "daily"
      time: "08:00"
    groups:
      security:
        patterns:
          - "PyJWT"
          - "passlib"
          - "bcrypt"
      quality:
        patterns:
          - "ruff"
          - "ty"
          - "prek"
          - "types-*"
          - "sqlalchemy-stubs"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    allow:
      - dependency-name: "ghcr.io/astral-sh/uv"
      - dependency-name: "localstack/localstack"
