# (generated with --quick)

import sqlalchemy.exc
from typing import Any, Generator, List, Type

CircularDependencyError: Type[sqlalchemy.exc.CircularDependencyError]
__all__: List[str]
util: module

def _gen_edges(edges) -> set: ...
def find_cycles(tuples, allitems) -> set: ...
def sort(tuples, allitems, deterministic_order = ...) -> Generator[Any, Any, None]: ...
def sort_as_subsets(tuples, allitems, deterministic_order = ...) -> Generator[set, Any, None]: ...
