"""initial

Revision ID: 9700bbccb2f1
Revises:
Create Date: 2026-04-18 08:05:12.294228

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9700bbccb2f1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("telegram_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("slack_hook", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "webhooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cameras",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("angle_of_view", sa.Float(), nullable=False),
        sa.Column("elevation", sa.Float(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("is_trustable", sa.Boolean(), nullable=False),
        sa.Column("last_active_at", sa.DateTime(), nullable=True),
        sa.Column("last_image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("camera_ip", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("device_ip", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "AGENT", "USER", name="userrole"), nullable=False),
        sa.Column("login", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(length=70), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_login"), "users", ["login"], unique=True)
    op.create_table(
        "poses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("camera_id", sa.Integer(), nullable=False),
        sa.Column("azimuth", sa.Float(), nullable=False),
        sa.Column("patrol_id", sa.Integer(), nullable=True),
        sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "occlusion_masks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pose_id", sa.Integer(), nullable=False),
        sa.Column("mask", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pose_id"],
            ["poses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sequences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("camera_id", sa.Integer(), nullable=False),
        sa.Column("pose_id", sa.Integer(), nullable=True),
        sa.Column("camera_azimuth", sa.Float(), nullable=False),
        sa.Column(
            "is_wildfire", sa.Enum("WILDFIRE_SMOKE", "OTHER_SMOKE", "OTHER", name="annotationtype"), nullable=True
        ),
        sa.Column("sequence_azimuth", sa.Float(), nullable=True),
        sa.Column("cone_angle", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pose_id"],
            ["poses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alerts_sequences",
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("sequence_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sequence_id"],
            ["sequences.id"],
        ),
        sa.PrimaryKeyConstraint("alert_id", "sequence_id"),
    )
    op.create_table(
        "detections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("camera_id", sa.Integer(), nullable=False),
        sa.Column("pose_id", sa.Integer(), nullable=False),
        sa.Column("sequence_id", sa.Integer(), nullable=True),
        sa.Column("bucket_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bbox", sqlmodel.sql.sqltypes.AutoString(length=37), nullable=False),
        sa.Column("others_bboxes", sqlmodel.sql.sqltypes.AutoString(length=148), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["camera_id"],
            ["cameras.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pose_id"],
            ["poses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sequence_id"],
            ["sequences.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("detections")
    op.drop_table("alerts_sequences")
    op.drop_table("sequences")
    op.drop_table("occlusion_masks")
    op.drop_table("poses")
    op.drop_index(op.f("ix_users_login"), table_name="users")
    op.drop_table("users")
    op.drop_table("cameras")
    op.drop_table("alerts")
    op.drop_table("webhooks")
    op.drop_table("organizations")
    sa.Enum(name="annotationtype").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="userrole").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
