# (generated with --quick)

from typing import Any, Type, TypeVar, Union

ensureString: Type[bytes]
implementation: str
long: Type[int]
null: bytes
platform: module
sys: module

_T0 = TypeVar('_T0')

def a2b_hex(__hexstr: Union[bytes, str]) -> bytes: ...
def b2a_hex(__data: bytes) -> bytes: ...
def bitLength(number) -> int: ...
def from_bytes(octets, signed = ...) -> int: ...
def oct2int(x: _T0) -> _T0: ...
def to_bytes(value, signed = ..., length = ...) -> Any: ...
