# (generated with --quick)

from typing import Any, Tuple, Type, TypeVar

ensureString: Type[bytes]
ints2octs: Type[bytes]
null: bytes
version_info: Tuple[int, int, int, str, int]

_T0 = TypeVar('_T0')

def int2oct(x) -> bytes: ...
def isOctetsType(s) -> bool: ...
def isStringType(s) -> bool: ...
def oct2int(x: _T0) -> _T0: ...
def octs2ints(x: _T0) -> _T0: ...
def octs2str(x) -> Any: ...
def str2octs(x) -> Any: ...
