# (generated with --quick)

import starlette.responses
from typing import Any, Dict, Optional, Set, Type, Union

HTMLResponse: Type[starlette.responses.HTMLResponse]
json: module

def get_redoc_html(*, openapi_url: str, title: str, redoc_js_url: str = ..., redoc_favicon_url: str = ..., with_google_fonts: bool = ...) -> starlette.responses.HTMLResponse: ...
def get_swagger_ui_html(*, openapi_url: str, title: str, swagger_js_url: str = ..., swagger_css_url: str = ..., swagger_favicon_url: str = ..., oauth2_redirect_url: Optional[str] = ..., init_oauth: Optional[dict] = ...) -> starlette.responses.HTMLResponse: ...
def get_swagger_ui_oauth2_redirect_html() -> starlette.responses.HTMLResponse: ...
def jsonable_encoder(obj, include: Optional[Union[Dict[Union[int, str], Any], Set[Union[int, str]]]] = ..., exclude: Optional[Union[Dict[Union[int, str], Any], Set[Union[int, str]]]] = ..., by_alias: bool = ..., exclude_unset: bool = ..., exclude_defaults: bool = ..., exclude_none: bool = ..., custom_encoder: dict = ..., sqlalchemy_safe: bool = ...) -> Any: ...
