# (generated with --quick)

from typing import Any

ARRAY: Any
BIGINT: Any
BINARY: Any
BLANK_SCHEMA: Any
BLOB: Any
BOOLEAN: Any
BigInteger: Any
Binary: Any
Boolean: Any
CHAR: Any
CLOB: Any
CheckConstraint: Any
Column: Any
ColumnDefault: Any
Computed: Any
Constraint: Any
DATE: Any
DATETIME: Any
DDL: Any
DECIMAL: Any
Date: Any
DateTime: Any
DefaultClause: Any
Enum: Any
FLOAT: Any
FetchedValue: Any
Float: Any
ForeignKey: Any
ForeignKeyConstraint: Any
INT: Any
INTEGER: Any
IdentityOptions: Any
Index: Any
Integer: Any
Interval: Any
JSON: Any
LargeBinary: Any
MetaData: Any
NCHAR: Any
NUMERIC: Any
NVARCHAR: Any
Numeric: Any
PassiveDefault: Any
PickleType: Any
PrimaryKeyConstraint: Any
REAL: Any
SMALLINT: Any
Sequence: Any
SmallInteger: Any
String: Any
TEXT: Any
TIME: Any
TIMESTAMP: Any
Table: Any
Text: Any
ThreadLocalMetaData: Any
Time: Any
TypeDecorator: Any
Unicode: Any
UnicodeText: Any
UniqueConstraint: Any
VARBINARY: Any
VARCHAR: Any
__all__: list
__version__: str
_util: module
alias: Any
all_: Any
and_: Any
any_: Any
asc: Any
between: Any
bindparam: Any
case: Any
cast: Any
collate: Any
column: Any
delete: Any
desc: Any
distinct: Any
except_: Any
except_all: Any
exists: Any
extract: Any
false: Any
func: Any
funcfilter: Any
insert: Any
intersect: Any
intersect_all: Any
join: Any
lateral: Any
literal: Any
literal_column: Any
modifier: Any
not_: Any
null: Any
nullsfirst: Any
nullslast: Any
or_: Any
outerjoin: Any
outparam: Any
over: Any
select: Any
subquery: Any
table: Any
tablesample: Any
text: Any
true: Any
tuple_: Any
type_coerce: Any
union: Any
union_all: Any
update: Any
within_group: Any

def __go(lcls) -> None: ...
def create_engine(*args, **kwargs) -> Any: ...
def engine_from_config(configuration, prefix = ..., **kwargs) -> Any: ...
def inspect(subject, raiseerr = ...) -> Any: ...
