# (generated with --quick)

from typing import Any, Dict, Generator, List, NoReturn, Tuple

COMMENTCHARS: str
__all__: List[str]

class IniConfig:
    _sources: Dict[Tuple[Any, Any], Any]
    path: str
    sections: Dict[Any, dict]
    def __contains__(self, arg) -> bool: ...
    def __getitem__(self, name) -> SectionWrapper: ...
    def __init__(self, path, data = ...) -> None: ...
    def __iter__(self) -> Generator[SectionWrapper, Any, None]: ...
    def _parse(self, line_iter) -> List[tuple]: ...
    def _parseline(self, line, lineno) -> Tuple[Any, Any]: ...
    def _raise(self, lineno, msg) -> NoReturn: ...
    def get(self, section, name, default = ..., convert = ...) -> Any: ...
    def lineof(self, section, name = ...) -> Any: ...

class ParseError(Exception):
    lineno: Any
    msg: Any
    path: Any
    def __init__(self, path, lineno, msg) -> None: ...
    def __str__(self) -> str: ...

class SectionWrapper:
    config: Any
    name: Any
    def __getitem__(self, key) -> Any: ...
    def __init__(self, config, name) -> None: ...
    def __iter__(self) -> Generator[Any, Any, None]: ...
    def get(self, key, default = ..., convert = ...) -> Any: ...
    def items(self) -> Generator[Tuple[Any, Any], Any, None]: ...
    def lineof(self, name) -> Any: ...

def iscommentline(line) -> bool: ...
