# (generated with --quick)

from typing import Any, Coroutine, Dict, Optional, Tuple

BaseModel: Any
HTTPException: Any
Path: Any
Table: Any
UserAuth: Any
UserCreation: Any
UserCred: Any
UserCredHash: Any
crud: module
security: module

def create_entry(table, payload) -> Coroutine[Any, Any, dict]: ...
def create_user(user_table, payload) -> Coroutine[Any, Any, dict]: ...
def delete_entry(table, entry_id: int = ...) -> coroutine: ...
def fetch_entries(table, query_filter: Optional[Tuple[str, Any]] = ...) -> coroutine: ...
def fetch_entry(table, query_filter: Tuple[str, Any]) -> coroutine: ...
def get_entry(table, entry_id: int = ...) -> coroutine: ...
def update_entry(table, payload, entry_id: int = ...) -> Coroutine[Any, Any, dict]: ...
def update_user_pwd(user_table, payload, entry_id: int = ...) -> Coroutine[Any, Any, Dict[str, Any]]: ...
