# (generated with --quick)

from typing import Any, Dict, Union

FULL_PAYLOAD: Dict[str, Union[int, str]]
MIN_PAYLOAD: Dict[str, int]
crud: module
json: module
pytest: module
test_update_media_invalid: Any

def test_create_media(test_app, monkeypatch) -> None: ...
def test_create_media_invalid_json(test_app) -> None: ...
def test_fetch_medias(test_app, monkeypatch) -> None: ...
def test_get_media(test_app, monkeypatch) -> None: ...
def test_get_media_incorrect_id(test_app, monkeypatch) -> None: ...
def test_remove_media(test_app, monkeypatch) -> None: ...
def test_remove_media_incorrect_id(test_app, monkeypatch) -> None: ...
def test_update_media(test_app, monkeypatch) -> None: ...
