# (generated with --quick)

from typing import Any, Dict

BASE_PAYLOAD: Dict[str, str]
FULL_PAYLOAD: Dict[str, str]
MIN_PAYLOAD: Dict[str, str]
REPLY_PAYLOAD: Dict[str, str]
crud: module
json: module
pytest: module
test_update_access_invalid: Any

def test_create_access(test_app, monkeypatch) -> None: ...
def test_create_access_invalid_json(test_app) -> None: ...
def test_fetch_access(test_app, monkeypatch) -> None: ...
def test_get_access(test_app, monkeypatch) -> None: ...
def test_get_access_incorrect_id(test_app, monkeypatch) -> None: ...
def test_remove_access(test_app, monkeypatch) -> None: ...
def test_remove_access_incorrect_id(test_app, monkeypatch) -> None: ...
def test_update_access(test_app, monkeypatch) -> None: ...
