# (generated with --quick)

from typing import Any, Dict, Optional, Union

FULL_PAYLOAD: Dict[str, Optional[Union[float, str]]]
MIN_PAYLOAD: Dict[str, float]
crud: module
json: module
pytest: module
test_update_event_invalid: Any

def test_create_event(test_app, monkeypatch) -> None: ...
def test_create_event_invalid_json(test_app) -> None: ...
def test_fetch_events(test_app, monkeypatch) -> None: ...
def test_get_event(test_app, monkeypatch) -> None: ...
def test_get_event_incorrect_id(test_app, monkeypatch) -> None: ...
def test_remove_event(test_app, monkeypatch) -> None: ...
def test_remove_event_incorrect_id(test_app, monkeypatch) -> None: ...
def test_update_event(test_app, monkeypatch) -> None: ...
