# (generated with --quick)

from typing import Any, Dict, Optional, Union

FULL_PAYLOAD: Dict[str, Optional[Union[int, str]]]
MIN_PAYLOAD: Dict[str, int]
crud: module
json: module
pytest: module
test_update_alert_invalid: Any

def test_create_alert(test_app, monkeypatch) -> None: ...
def test_create_alert_invalid_json(test_app) -> None: ...
def test_fetch_alerts(test_app, monkeypatch) -> None: ...
def test_get_alert(test_app, monkeypatch) -> None: ...
def test_get_alert_incorrect_id(test_app, monkeypatch) -> None: ...
def test_remove_alert(test_app, monkeypatch) -> None: ...
def test_remove_alert_incorrect_id(test_app, monkeypatch) -> None: ...
def test_update_alert(test_app, monkeypatch) -> None: ...
