# (generated with --quick)

from typing import Any

crud: module
json: module
pytest: module
test_update_user_info_invalid: Any
test_update_user_pwd_invalid: Any

def test_create_user(test_app, monkeypatch) -> None: ...
def test_create_user_invalid_json(test_app) -> None: ...
def test_fetch_users(test_app, monkeypatch) -> None: ...
def test_get_me(test_app) -> None: ...
def test_get_user(test_app, monkeypatch) -> None: ...
def test_get_user_incorrect_id(test_app, monkeypatch) -> None: ...
def test_remove_note_incorrect_id(test_app, monkeypatch) -> None: ...
def test_remove_user(test_app, monkeypatch) -> None: ...
def test_update_user_info(test_app, monkeypatch) -> None: ...
def test_update_user_pwd(test_app, monkeypatch) -> None: ...
