# (generated with --quick)

from typing import Any, Dict, Union

FULL_PAYLOAD: Dict[str, Union[float, str]]
MIN_PAYLOAD: Dict[str, Union[float, str]]
crud: module
json: module
pytest: module
test_update_site_invalid: Any

def test_create_site(test_app, monkeypatch) -> None: ...
def test_create_site_invalid_json(test_app) -> None: ...
def test_fetch_sites(test_app, monkeypatch) -> None: ...
def test_get_site(test_app, monkeypatch) -> None: ...
def test_get_site_incorrect_id(test_app, monkeypatch) -> None: ...
def test_remove_site(test_app, monkeypatch) -> None: ...
def test_remove_site_incorrect_id(test_app, monkeypatch) -> None: ...
def test_update_site(test_app, monkeypatch) -> None: ...
