# (generated with --quick)

from typing import Any, Dict, Optional, Union

FULL_PAYLOAD: Dict[str, Optional[Union[int, str]]]
MIN_PAYLOAD: Dict[str, Union[int, str]]
crud: module
json: module
pytest: module
test_update_device_invalid: Any

def test_create_device(test_app, monkeypatch) -> None: ...
def test_create_device_invalid_json(test_app) -> None: ...
def test_fetch_devices(test_app, monkeypatch) -> None: ...
def test_fetch_my_devices(test_app, monkeypatch) -> None: ...
def test_get_device(test_app, monkeypatch) -> None: ...
def test_get_device_incorrect_id(test_app, monkeypatch) -> None: ...
def test_remove_device(test_app, monkeypatch) -> None: ...
def test_remove_device_incorrect_id(test_app, monkeypatch) -> None: ...
def test_update_device(test_app, monkeypatch) -> None: ...
