# (generated with --quick)

from typing import Any, Dict, Optional

FULL_PAYLOAD: Dict[str, Optional[int]]
MIN_PAYLOAD: Dict[str, int]
crud: module
json: module
pytest: module
test_update_installation_invalid: Any

def test_create_installation(test_app, monkeypatch) -> None: ...
def test_create_installation_invalid_json(test_app) -> None: ...
def test_fetch_installations(test_app, monkeypatch) -> None: ...
def test_get_installation(test_app, monkeypatch) -> None: ...
def test_get_installation_incorrect_id(test_app, monkeypatch) -> None: ...
def test_remove_installation(test_app, monkeypatch) -> None: ...
def test_remove_installation_incorrect_id(test_app, monkeypatch) -> None: ...
def test_update_installation(test_app, monkeypatch) -> None: ...
