{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.name }}
  version: "{{ data.version }}"

source:
  fn: {{ data.name }}-{{ data.version }}.tar.gz
  url: ../dist/{{ data.name }}-{{ data.version }}.tar.gz

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:

  host:
    - python>=3.7

  run:
    - requests >=2.24.0

test:
  # Python imports
  imports:
    - pyroclient.client
  requires:
    - python

about:
  home: {{ data.get('url') }}
  license: {{ data['license'] }}
  license_url: https://github.com/pyronear/pyro-api/blob/master/LICENSE
  license_file: LICENSE
  summary: {{ data['description'] }}
  description: |
    {{ data['long_description'] | replace("\n", "\n    ") | replace("#", '\#')}}
  doc_url: https://pyronear.org/pyro-api/
  dev_url: {{ data.get('url') }}