# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#loading-data-from-other-files
# https://github.com/conda/conda-build/pull/4480
# for conda-build > 3.21.9
# {% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
# {% set project = pyproject.get('project') %}
# {% set urls = pyproject.get('project', {}).get('urls') %}
package:
  name: pyroclient
  version: "{{ environ.get('BUILD_VERSION') }}"

source:
  fn: pyroclient-{{ environ.get('BUILD_VERSION') }}.tar.gz
  url: ../dist/pyroclient-{{ environ.get('BUILD_VERSION') }}.tar.gz

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python>=3.6, <4.0
    - setuptools

  run:
    - python>=3.6, <4.0
    - requests >=2.24.0, <3.0.0

test:
  # Python imports
  imports:
    - pyroclient
    - pyroclient.client
  requires:
    - python

about:
  home: https://github.com/frgfm/pyro-api/client
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Python Client for Pyronear wildfire alert API'
  # description: |
  #   {{ data['long_description'] | replace("\n", "\n    ") | replace("#", '\#')}}
  doc_url: https://pyronear.org/pyro-api
  dev_url: https://github.com/pyronear/pyro-api/client
