# (generated with --quick)

from typing import Any, Tuple

bisect: module

def _decode_range(r) -> Tuple[Any, Any]: ...
def _encode_range(start, end) -> Any: ...
def intranges_contain(int_, ranges) -> bool: ...
def intranges_from_list(list_) -> tuple: ...
