# (generated with --quick)

from typing import List, Tuple, Union

__version__: str
uts46data: tuple

def _seg_0() -> list: ...
def _seg_1() -> list: ...
def _seg_10() -> list: ...
def _seg_11() -> list: ...
def _seg_12() -> list: ...
def _seg_13() -> list: ...
def _seg_14() -> list: ...
def _seg_15() -> list: ...
def _seg_16() -> list: ...
def _seg_17() -> list: ...
def _seg_18() -> list: ...
def _seg_19() -> list: ...
def _seg_2() -> list: ...
def _seg_20() -> list: ...
def _seg_21() -> list: ...
def _seg_22() -> list: ...
def _seg_23() -> list: ...
def _seg_24() -> list: ...
def _seg_25() -> list: ...
def _seg_26() -> list: ...
def _seg_27() -> list: ...
def _seg_28() -> list: ...
def _seg_29() -> list: ...
def _seg_3() -> list: ...
def _seg_30() -> list: ...
def _seg_31() -> list: ...
def _seg_32() -> list: ...
def _seg_33() -> list: ...
def _seg_34() -> list: ...
def _seg_35() -> list: ...
def _seg_36() -> list: ...
def _seg_37() -> list: ...
def _seg_38() -> list: ...
def _seg_39() -> list: ...
def _seg_4() -> list: ...
def _seg_40() -> list: ...
def _seg_41() -> list: ...
def _seg_42() -> list: ...
def _seg_43() -> list: ...
def _seg_44() -> list: ...
def _seg_45() -> list: ...
def _seg_46() -> list: ...
def _seg_47() -> list: ...
def _seg_48() -> list: ...
def _seg_49() -> list: ...
def _seg_5() -> list: ...
def _seg_50() -> list: ...
def _seg_51() -> list: ...
def _seg_52() -> list: ...
def _seg_53() -> list: ...
def _seg_54() -> list: ...
def _seg_55() -> list: ...
def _seg_56() -> list: ...
def _seg_57() -> list: ...
def _seg_58() -> list: ...
def _seg_59() -> list: ...
def _seg_6() -> list: ...
def _seg_60() -> list: ...
def _seg_61() -> list: ...
def _seg_62() -> list: ...
def _seg_63() -> list: ...
def _seg_64() -> list: ...
def _seg_65() -> list: ...
def _seg_66() -> list: ...
def _seg_67() -> list: ...
def _seg_68() -> list: ...
def _seg_69() -> list: ...
def _seg_7() -> list: ...
def _seg_70() -> list: ...
def _seg_71() -> list: ...
def _seg_72() -> list: ...
def _seg_73() -> list: ...
def _seg_74() -> list: ...
def _seg_75() -> list: ...
def _seg_76() -> list: ...
def _seg_77() -> list: ...
def _seg_78() -> list: ...
def _seg_79() -> List[Tuple[Union[int, str], ...]]: ...
def _seg_8() -> list: ...
def _seg_9() -> list: ...
