# (generated with --quick)

from typing import Any, Dict, Tuple, Type

ModuleType: Type[module]
__version__: str
os: module
sys: module

class ApiModule(module):
    _ApiModule__doc: Any
    __all__: Any
    __dict__: Any
    __doc__: Any
    __implprefix__: Any
    __map__: Dict[Any, Tuple[Any, Any]]
    def _ApiModule__docget(self) -> Any: ...
    def _ApiModule__docset(self, value) -> None: ...
    def _ApiModule__makeattr(self, name) -> Any: ...
    def __getattr__(self, name) -> Any: ...
    def __init__(self, name, importspec, implprefix = ..., attr = ...) -> None: ...
    def __repr__(self) -> str: ...

def AliasModule(modname, modpath, attrname = ...) -> Any: ...
def _py_abspath(path) -> Any: ...
def distribution_version(name) -> Any: ...
def importobj(modpath, attrname) -> Any: ...
def initpkg(pkgname, exportdefs, attr = ..., eager = ...) -> None: ...
