# (generated with --quick)

import __future__

Infinity: InfinityType
NegativeInfinity: NegativeInfinityType
absolute_import: __future__._Feature
division: __future__._Feature
print_function: __future__._Feature

class InfinityType:
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __neg__(self: object) -> NegativeInfinityType: ...
    def __repr__(self) -> str: ...

class NegativeInfinityType:
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __neg__(self: object) -> InfinityType: ...
    def __repr__(self) -> str: ...
