# (generated with --quick)

import __future__
from typing import Any, Callable, Dict, List

CONDITIONAL_NAMES: Dict[str, Callable[[], Any]]
absolute_import: __future__._Feature
division: __future__._Feature
print_function: __future__._Feature

def cryptography_has_102_verification() -> List[str]: ...
def cryptography_has_110_verification_params() -> List[str]: ...
def cryptography_has_cipher_details() -> List[str]: ...
def cryptography_has_custom_ext() -> List[str]: ...
def cryptography_has_ec2m() -> List[str]: ...
def cryptography_has_ed25519() -> List[str]: ...
def cryptography_has_ed448() -> List[str]: ...
def cryptography_has_engine() -> List[str]: ...
def cryptography_has_evp_digestfinal_xof() -> List[str]: ...
def cryptography_has_evp_pkey_dhx() -> List[str]: ...
def cryptography_has_evp_pkey_get_set_tls_encodedpoint() -> List[str]: ...
def cryptography_has_fips() -> List[str]: ...
def cryptography_has_keylog() -> List[str]: ...
def cryptography_has_locking_callbacks() -> List[str]: ...
def cryptography_has_mem_functions() -> List[str]: ...
def cryptography_has_oneshot_evp_digest_sign_verify() -> List[str]: ...
def cryptography_has_openssl_cleanup() -> List[str]: ...
def cryptography_has_poly1305() -> List[str]: ...
def cryptography_has_psk() -> List[str]: ...
def cryptography_has_raw_key() -> List[str]: ...
def cryptography_has_rsa_oaep_label() -> List[str]: ...
def cryptography_has_rsa_oaep_md() -> List[str]: ...
def cryptography_has_scrypt() -> List[str]: ...
def cryptography_has_sct() -> List[str]: ...
def cryptography_has_set_cert_cb() -> List[str]: ...
def cryptography_has_srtp() -> List[str]: ...
def cryptography_has_ssl3_method() -> List[str]: ...
def cryptography_has_ssl_sigalgs() -> List[str]: ...
def cryptography_has_ssl_st() -> List[str]: ...
def cryptography_has_tls_st() -> List[str]: ...
def cryptography_has_tlsv13() -> List[str]: ...
def cryptography_has_verified_chain() -> List[str]: ...
def cryptography_has_x25519() -> List[str]: ...
def cryptography_has_x448() -> List[str]: ...
def cryptography_has_x509_store_ctx_get_issuer() -> List[str]: ...
