"""Add localization column in Alert table

Revision ID: 92e49f7d80ae
Revises: cd701efe364f
Create Date: 2023-10-18 18:51:40.632557

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "92e49f7d80ae"
down_revision = "cd701efe364f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alerts", sa.Column("localization", sa.String(length=200), nullable=True))
    op.alter_column(
        "alerts",
        "azimuth",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=4, asdecimal=True),
        existing_nullable=True,
    )
    op.alter_column(
        "alerts", "lat", existing_type=sa.REAL(), type_=sa.Float(precision=4, asdecimal=True), existing_nullable=True
    )
    op.alter_column(
        "alerts", "lon", existing_type=sa.REAL(), type_=sa.Float(precision=4, asdecimal=True), existing_nullable=True
    )
    op.alter_column(
        "devices",
        "angle_of_view",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2, asdecimal=True),
        existing_nullable=True,
    )
    op.alter_column(
        "devices",
        "elevation",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=1, asdecimal=True),
        existing_nullable=True,
    )
    op.alter_column(
        "devices", "lat", existing_type=sa.REAL(), type_=sa.Float(precision=4, asdecimal=True), existing_nullable=True
    )
    op.alter_column(
        "devices", "lon", existing_type=sa.REAL(), type_=sa.Float(precision=4, asdecimal=True), existing_nullable=True
    )
    op.alter_column(
        "devices",
        "azimuth",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=1, asdecimal=True),
        existing_nullable=True,
    )
    op.alter_column(
        "devices", "pitch", existing_type=sa.REAL(), type_=sa.Float(precision=1, asdecimal=True), existing_nullable=True
    )
    op.alter_column(
        "events", "lat", existing_type=sa.REAL(), type_=sa.Float(precision=4, asdecimal=True), existing_nullable=True
    )
    op.alter_column(
        "events", "lon", existing_type=sa.REAL(), type_=sa.Float(precision=4, asdecimal=True), existing_nullable=True
    )
    op.alter_column(
        "sites", "lat", existing_type=sa.REAL(), type_=sa.Float(precision=4, asdecimal=True), existing_nullable=True
    )
    op.alter_column(
        "sites", "lon", existing_type=sa.REAL(), type_=sa.Float(precision=4, asdecimal=True), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sites", "lon", existing_type=sa.Float(precision=4, asdecimal=True), type_=sa.REAL(), existing_nullable=True
    )
    op.alter_column(
        "sites", "lat", existing_type=sa.Float(precision=4, asdecimal=True), type_=sa.REAL(), existing_nullable=True
    )
    op.alter_column(
        "events", "lon", existing_type=sa.Float(precision=4, asdecimal=True), type_=sa.REAL(), existing_nullable=True
    )
    op.alter_column(
        "events", "lat", existing_type=sa.Float(precision=4, asdecimal=True), type_=sa.REAL(), existing_nullable=True
    )
    op.alter_column(
        "devices", "pitch", existing_type=sa.Float(precision=1, asdecimal=True), type_=sa.REAL(), existing_nullable=True
    )
    op.alter_column(
        "devices",
        "azimuth",
        existing_type=sa.Float(precision=1, asdecimal=True),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "devices", "lon", existing_type=sa.Float(precision=4, asdecimal=True), type_=sa.REAL(), existing_nullable=True
    )
    op.alter_column(
        "devices", "lat", existing_type=sa.Float(precision=4, asdecimal=True), type_=sa.REAL(), existing_nullable=True
    )
    op.alter_column(
        "devices",
        "elevation",
        existing_type=sa.Float(precision=1, asdecimal=True),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "devices",
        "angle_of_view",
        existing_type=sa.Float(precision=2, asdecimal=True),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.alter_column(
        "alerts", "lon", existing_type=sa.Float(precision=4, asdecimal=True), type_=sa.REAL(), existing_nullable=True
    )
    op.alter_column(
        "alerts", "lat", existing_type=sa.Float(precision=4, asdecimal=True), type_=sa.REAL(), existing_nullable=True
    )
    op.alter_column(
        "alerts",
        "azimuth",
        existing_type=sa.Float(precision=4, asdecimal=True),
        type_=sa.REAL(),
        existing_nullable=True,
    )
    op.drop_column("alerts", "localization")
    # ### end Alembic commands ###
