# (generated with --quick)

from typing import Any, List

__all__: List[str]
error: module

class TagMap:
    _TagMap__defaultType: Any
    _TagMap__presentTypes: Any
    _TagMap__skipTypes: Any
    __doc__: str
    defaultType: Any
    presentTypes: Any
    skipTypes: Any
    def __contains__(self, tagSet) -> bool: ...
    def __getitem__(self, tagSet) -> Any: ...
    def __init__(self, presentTypes = ..., skipTypes = ..., defaultType = ...) -> None: ...
    def __iter__(self) -> Any: ...
    def __repr__(self) -> str: ...
    def getDef(self) -> Any: ...
    def getNegMap(self) -> Any: ...
    def getPosMap(self) -> Any: ...
