# (generated with --quick)

from typing import Any

os: module

def is_appengine() -> Any: ...
def is_appengine_sandbox() -> Any: ...
def is_local_appengine() -> bool: ...
def is_prod_appengine() -> bool: ...
def is_prod_appengine_mvms() -> bool: ...
