# (generated with --quick)

import __future__
from typing import Any, Type
import urllib3.util.wait

HAS_IPV6: bool
NoWayToWaitForSocketError: Type[urllib3.util.wait.NoWayToWaitForSocketError]
_appengine_environ: module
absolute_import: __future__._Feature
socket: module

def _has_ipv6(host) -> bool: ...
def _set_socket_options(sock, options) -> None: ...
def allowed_gai_family() -> socket.AddressFamily: ...
def create_connection(address, timeout = ..., source_address = ..., socket_options = ...) -> socket.socket: ...
def is_connection_dropped(conn) -> Any: ...
def wait_for_read(sock, timeout = ...) -> Any: ...
