# (generated with --quick)

import functools
from typing import Any, List, NoReturn, Type

__all__: List[str]
errno: module
partial: Type[functools.partial]
select: module
sys: module

class NoWayToWaitForSocketError(Exception): ...

def _have_working_poll() -> bool: ...
def _retry_on_intr(fn, timeout) -> Any: ...
def monotonic() -> float: ...
def null_wait_for_socket(*args, **kwargs) -> NoReturn: ...
def poll_wait_for_socket(sock, read = ..., write = ..., timeout = ...) -> bool: ...
def select_wait_for_socket(sock, read = ..., write = ..., timeout = ...) -> bool: ...
def wait_for_read(sock, timeout = ...) -> Any: ...
def wait_for_socket(*args, **kwargs) -> Any: ...
def wait_for_write(sock, timeout = ...) -> Any: ...
