# (generated with --quick)

from typing import Any, List, Optional, Tuple

BaseModel: Any
Table: Any
database: Any

def delete(entry_id: int, table) -> coroutine: ...
def fetch_all(table, query_filters: Optional[List[Tuple[str, Any]]] = ...) -> coroutine: ...
def fetch_one(table, query_filters: List[Tuple[str, Any]]) -> coroutine: ...
def get(entry_id: int, table) -> coroutine: ...
def post(payload, table) -> coroutine: ...
def put(entry_id: int, payload, table) -> coroutine: ...
