FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9-alpine3.14

WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH "${PYTHONPATH}:/app"

# copy requirements file
COPY app/requirements.txt /app/requirements.txt

# install dependencies
RUN set -eux \
    && apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev libmagic \
    && pip install --no-cache-dir uv \
    && uv pip install --no-cache --system -r /app/requirements.txt \
    && apk del --purge gcc musl-dev postgresql-dev \
    && rm -rf /root/.cache/pip

# copy project
COPY app /app/app
COPY alembic.ini /app/alembic.ini
COPY alembic /app/alembic
COPY tests /app/tests
