# (generated with --quick)

from typing import Any, TypeVar

_TTagTracerSub = TypeVar('_TTagTracerSub', bound=TagTracerSub)

class TagTracer:
    _tags2proc: dict
    _writer: Any
    indent: int
    def __init__(self) -> None: ...
    def _format_message(self, tags, args) -> str: ...
    def _processmessage(self, tags, args) -> None: ...
    def get(self, name) -> TagTracerSub: ...
    def setprocessor(self, tags, processor) -> None: ...
    def setwriter(self, writer) -> None: ...

class TagTracerSub:
    root: Any
    tags: Any
    def __call__(self, *args) -> None: ...
    def __init__(self, root, tags) -> None: ...
    def get(self: _TTagTracerSub, name) -> _TTagTracerSub: ...
