# (generated with --quick)

import threading
from typing import Any, Type

_local: threading.local
local: Type[threading.local]

def get_current_context(silent = ...) -> Any: ...
def pop_context() -> None: ...
def push_context(ctx) -> None: ...
def resolve_color_default(color = ...) -> Any: ...
