# (generated with --quick)

from typing import NoReturn

class Key:
    __doc__: str
    def __init__(self, key, algorithm) -> None: ...
    def public_key(self) -> NoReturn: ...
    def sign(self, msg) -> NoReturn: ...
    def to_dict(self) -> NoReturn: ...
    def to_pem(self) -> NoReturn: ...
    def verify(self, msg, sig) -> NoReturn: ...
