name: doc-deploy
on:
  push:
    branches: master

jobs:
  docs-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Cache python modules
        uses: actions/cache@v2
        env:
          cache-name: client-reqs
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-deps-${{ env.cache-name }}-${{ hashFiles('client/requirements.txt') }}-${{ hashFiles('client/**/*.py') }}
          restore-keys: |
            ${{ runner.os }}-deps-${{ env.cache-name }}-${{ hashFiles('client/requirements.txt') }}-
            ${{ runner.os }}-deps-${{ env.cache-name }}-
            ${{ runner.os }}-deps-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e client/.
          pip install -r client/docs/requirements.txt

      - name: Build documentation
        run: |
          sphinx-build client/docs/source client/docs/build -a -v

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: 'client/docs/build'
          COMMIT_MESSAGE: '[skip ci] Documentation updates'
          CLEAN: true
          SSH: true
      
