name: docker-publish

on:
  release:
    types: [ published ]

jobs:
  dockerhub-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PW }}
          repository: pyronear/pyro-api
          tag_with_ref: true
