name: scripts

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  PYTHON_VERSION: "3.11"
  UV_VERSION: "0.11.14"

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      - uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
      - name: Run the backend & the test
        env:
          SUPERUSER_LOGIN: dummy_login
          SUPERUSER_PWD: dummy&P@ssw0rd!
          POSTGRES_USER: dummy_pg_user
          POSTGRES_PASSWORD: dummy_pg_pwd
          POSTGRES_DB: dummy_pg_db
        run: |
          docker compose -f docker-compose.dev.yml up -d --build --wait
          uv run --group e2e python scripts/test_e2e.py
