name: style

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  PYTHON_VERSION: "3.11"
  UV_VERSION: "0.11.14"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      - uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
      - name: Run ruff
        run: |
          uv run --group quality ruff --version
          make ruff-check

  ty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      - uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
      - name: Run ty
        run: |
          uv run --group quality ty --version
          make typing-check

  precommit-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
      - uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
      - name: Run prek hooks
        run: |
          uv run --group quality prek --version
          make precommit
